version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
      - ./src/storage:/var/www/storage
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_DATABASE=incidencias_db
      - DB_USERNAME=root
      - DB_PASSWORD=password

  webserver:
    image: nginx:alpine
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: incidencias_db
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
